PhotoGallery.Web/Controllers/AlbumController.cs
using PhotoGallery.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhotoGallery.Web.Controllers
{
    public class AlbumController : Controller
    {
        PhotoGalleryContext context = new PhotoGalleryContext();

        // GET: /Album/
        public ActionResult Index()
        {
            return View(context.Albums.ToList());
        }
	}
}

PhotoGallery.Web/Controllers/HomeController.cs
using PhotoGallery.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhotoGallery.Web.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/
        public ActionResult Index()
        {
            return View();
        }
	}
}

PhotoGallery.Web/Views/Album/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

PhotoGallery.Web/Views/Home/Index.cshtml
@model IEnumerable<PhotoGallery.Model.Album>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

PhotoGallery.Web/Views/Shared/_Layout.cshtml
@using System.Web.Optimization

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <header>
        <h1>PhotoGallery</h1>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
            <ul class="nav">
                <li>
                    @Html.ActionLink("Home", "Index", "Home")
                </li>
                <li>
                    @Html.ActionLink("Gallery", "Index", "Album")
                </li>
            </ul>
        </div>

        </nav>
        <form class="navbar-form navbar-left" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
      </form>
    </header>
    <section>
        @RenderBody()
    </section>
    <footer>
        @DateTime.Now.Year - Yohan's PhotoGallery
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
</body>
</html>